# Generated by Django 5.2.1 on 2025-06-23 20:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sparkling', 'sparkling'), ('fortified', 'Fortified'), ('dessert', 'Dessert'), ('red', 'Red'), ('white', 'White'), ("rose'", "Rose'")], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('country', 'region'), name='unique-country-region')],
            },
        ),
        migrations.CreateModel(
            name='WineStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('dry', 'Dry'), ('off-dry', 'Off-dry'), ('sweet', 'Sweet')], max_length=50)),
                ('body', models.CharField(choices=[('light', 'Ligh-Bodied'), ('medium', 'Medium-Bodied'), ('full', 'Full-Bodied')], max_length=50)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('style', 'body'), name='unique-style-body')],
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2025)], verbose_name='Year of Production')),
                ('appelation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_api.appelation', verbose_name='Appelation')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_api.region')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_api.winestyle', verbose_name='Style & Body')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_api.winetype', verbose_name='Wine Type')),
            ],
        ),
    ]
