# Generated by Django 5.2.1 on 2025-07-26 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appelation',
            new_name='Appellation',
        ),
        migrations.RenameField(
            model_name='wine',
            old_name='appelation',
            new_name='appellation',
        ),
        migrations.AddField(
            model_name='wine',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='added by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0, verbose_name='quantity sold'),
        ),
        migrations.AddField(
            model_name='wine',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='sale price'),
        ),
        migrations.AddField(
            model_name='wine',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='quantity'),
        ),
    ]
