# Generated by Django 5.2.1 on 2025-07-26 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0003_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='sale_price',
            new_name='retail_price',
        ),
    ]
