# Generated by Django 5.2.1 on 2025-08-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0004_rename_sale_price_wine_retail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='retail price'),
        ),
    ]
