# Generated by Django 5.2.1 on 2025-08-05 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0005_alter_wine_retail_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appellation',
            new_name='AppellationModel',
        ),
        migrations.RenameModel(
            old_name='Region',
            new_name='RegionModel',
        ),
        migrations.RenameModel(
            old_name='Sale',
            new_name='SaleModel',
        ),
        migrations.RenameModel(
            old_name='Wine',
            new_name='WineModel',
        ),
        migrations.RenameModel(
            old_name='WineStyle',
            new_name='WineStyleModel',
        ),
        migrations.RenameModel(
            old_name='WineType',
            new_name='WineTypeModel',
        ),
    ]
