# Generated by Django 5.2.1 on 2025-09-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0006_rename_appellation_appellationmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemodel',
            name='refund_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
