# Generated by Django 5.2.1 on 2025-09-08 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0007_salemodel_refund_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='winemodel',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='wine_stock_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='winemodel',
            constraint=models.CheckConstraint(condition=models.Q(('retail_price__gt', models.F('price'))), name='retail_price_gt_price'),
        ),
        migrations.AddConstraint(
            model_name='winemodel',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_gte_0'),
        ),
    ]
