# Generated by Django 5.2.1 on 2025-09-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0008_winemodel_wine_stock_gte_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemodel',
            name='quantity_sold',
            field=models.PositiveIntegerField(),
        ),
    ]
