# Generated by Django 5.2.1 on 2025-09-08 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0009_alter_salemodel_quantity_sold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salemodel',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_sold__gt', 0)), name='quantity_sold_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='salemodel',
            constraint=models.CheckConstraint(condition=models.Q(('refund_qty__lte', models.F('quantity_sold'))), name='refund_qty_lte_quantity_sold'),
        ),
    ]
