# Generated by Django 5.2.1 on 2025-09-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_logmodel_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='action',
            field=models.CharField(choices=[('sale_created', 'Sale Created'), ('user_logged_in', 'User Logged In'), ('user_logged_out', 'User Logged Out'), ('user_registered', 'User Registered'), ('wine_deleted', 'Wine Deleted'), ('restock', 'Restock'), ('refund', 'Refund')], max_length=50),
        ),
    ]
